### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by 3dnettr** [Haiahemmohamed/Access-Control-with-NodeMCU-V3-MySQL-PHP#1]
Hello, I couldn't find the mysql file.

**Comment by Haiahemmohamed** [comment]
I'm so sorry mate for the long time to response!
You can create your own database file.

MYSQL file -----> https://github.com/Haiahemmohamed/Access-Control-with-NodeMCU-V3-MySQL-PHP/blob/master/nodemcu_rfidrc522_mysql.sql

You can use phpmyadmin panel and create your own DB
